#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""test_golden.py — 渲染器端到端 golden-file 快照测试（无网络，直接 python 运行）

堵住 v4.5 遗留缺口：渲染器全量输出此前只有核心逻辑单测，无端到端回归保护。
本测试用最小合法 fill 全量渲染，产物与入库快照逐字节比对（版本标记归一后），
任何渲染逻辑/模板改动导致的输出漂移都会报红。

更新快照（仅在有意修改渲染输出时）：GOLDEN_UPDATE=1 python test_golden.py
另含：--check CLI 退出码用例（合规 0 / 拒渲染 2），替代手工验证。
"""
import json
import os
import re
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import render_report as R
from test_render_core import minimal_fill

GOLDEN = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "golden", "minimal_fill.html")

_VERSION_MARK = re.compile(r"generated by render_report\.py v[\d.]+")


def _render_norm(fill) -> str:
    """全量渲染并归一化版本标记（版本号升级不应击穿快照）。"""
    with tempfile.TemporaryDirectory() as d:
        p = os.path.join(d, "_fill_g.json")
        with open(p, "w", encoding="utf-8") as fp:
            json.dump(fill, fp, ensure_ascii=False)
        out = R.render(p, out_path=os.path.join(d, "out.html"))
        html = open(out, encoding="utf-8").read()
    return _VERSION_MARK.sub("generated by render_report.py v*", html)


def test_golden_full_render():
    """端到端快照：当前渲染输出必须与入库 golden 逐字节一致（版本标记除外）。"""
    actual = _render_norm(minimal_fill())
    if os.environ.get("GOLDEN_UPDATE") == "1":
        os.makedirs(os.path.dirname(GOLDEN), exist_ok=True)
        with open(GOLDEN, "w", encoding="utf-8") as f:
            f.write(actual)
        print(f"GOLDEN_UPDATE：快照已重写 → {GOLDEN}")
        return
    assert os.path.exists(GOLDEN), \
        f"快照不存在：{GOLDEN}（首次运行请用 GOLDEN_UPDATE=1 生成）"
    expected = open(GOLDEN, encoding="utf-8").read()
    assert actual == expected, (
        "渲染输出与 golden 快照不一致——渲染逻辑或模板发生了非预期漂移。\n"
        "若为有意修改，运行 GOLDEN_UPDATE=1 python test_golden.py 更新快照，"
        "并在提交说明中写明改动原因。")


def test_golden_catches_mutation():
    """自证有效：fill 内容改动必须导致输出偏离快照（快照不是摆设）。"""
    if os.environ.get("GOLDEN_UPDATE") == "1":
        return  # 更新模式下快照尚未生成，跳过
    assert os.path.exists(GOLDEN), "依赖已生成的快照"
    expected = open(GOLDEN, encoding="utf-8").read()
    mutated = minimal_fill(company="变异股份", thesis_html="<p>完全不同的论点。</p>")
    actual = _render_norm(mutated)
    assert actual != expected, "fill 改动后输出仍等于快照——快照比对失效"


def _cli_check(fill) -> int:
    """以子进程跑 --check，返回退出码（0=通过，2=拒渲染）。"""
    with tempfile.TemporaryDirectory() as d:
        p = os.path.join(d, "_fill_c.json")
        with open(p, "w", encoding="utf-8") as fp:
            json.dump(fill, fp, ensure_ascii=False)
        r = subprocess.run([sys.executable,
                            os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                         "render_report.py"),
                            p, "--check"],
                           capture_output=True)
    return r.returncode


def test_check_cli_exit_codes():
    """--check 全流程退出码：合规 fill → 0；拒渲染 fill（缺 yellow_deductions）→ 2。"""
    assert _cli_check(minimal_fill()) == 0, "合规 fill 的 --check 必须退出 0"
    bad = minimal_fill()
    del bad["yellow_deductions"]
    assert _cli_check(bad) == 2, "缺必填键的 fill 的 --check 必须退出 2"


if __name__ == "__main__":
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    for t in tests:
        t()
        print(f"OK {t.__name__}")
    print(f"全部 {len(tests)} 项测试通过")
