#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""test_extract_review.py — extract_review 回测触发判定与锚点提取回归测试（无网络，直接 python 运行）"""
import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import extract_review as E

MARK = "<!-- generated by render_report.py v4.5 -->"

FAKE_REPORT = f"""<html><body>
<h1>测试股份（600000）</h1>
<span class="topbar-tag active">2026-08-08</span>
<div class="hero-track quality"><div class="s-label">质量分</div><div class="s-value">7.50</div></div>
<div class="hero-track valuation"><div class="s-label">估值分</div><div class="s-value">6.5</div></div>
<div class="hero-timing-mini">时机分 <span class="tv">5.50</span></div>
<div class="d-item"><div class="d-label">目标价区间（12个月）</div><div class="d-value">400-500<span class="unit"> 元</span></div><div class="d-sub">基础情景</div></div>
</body></html>{MARK}"""


def _write(d, name, content):
    p = os.path.join(d, name)
    with open(p, "w", encoding="utf-8") as f:
        f.write(content)
    return p


def test_find_prev_report():
    with tempfile.TemporaryDirectory() as d:
        old = _write(d, "测试股份-600000-7.50-6.5-2026-08-08.html", FAKE_REPORT)
        # 更新的同代码报告应胜出
        _write(d, "测试股份-600000-7.80-6.8-复盘-2026-08-20.html", FAKE_REPORT)
        # 无渲染器标记的手写产物必须被排除，哪怕日期更新
        _write(d, "测试股份-600000-9.99-9.9-2026-08-25.html",
               FAKE_REPORT.replace(MARK, ""))
        # 其他代码不相关
        _write(d, "别的公司-600001-8.0-8.0-2026-08-26.html", FAKE_REPORT)
        # 文件名无日期不算
        _write(d, "测试股份-600000-无日期.html", FAKE_REPORT)
        got = E.find_prev_report("600000", d)
        assert got and got.endswith("2026-08-20.html"), f"应取最新的带标记版本，实际 {got}"
        # 全部排除干净时返回 None
    with tempfile.TemporaryDirectory() as d2:
        _write(d2, "测试股份-600000-9.9-9.9-2026-08-25.html", "<html>无标记</html>")
        assert E.find_prev_report("600000", d2) is None
        assert E.find_prev_report("600000", d2) is None  # 幂等
    print("OK find_prev_report（最新日期 / 无标记排除 / 他代码排除 / 空目录 None）")


def test_find_include_unmarked():
    """宽松档：无标记的 pre-v4.3 旧报告参与匹配；同日期带标记者优先。"""
    with tempfile.TemporaryDirectory() as d:
        unmarked = _write(d, "腾讯控股-00700-6.93-8.2-复盘-2026-08-23.html",
                          "<html><body>pre-v4.3 无标记</body></html>")
        assert E.find_prev_report("00700", d) is None, "严格档仍须排除无标记"
        got = E.find_prev_report("00700", d, include_unmarked=True)
        assert got == unmarked, f"宽松档应命中无标记旧报告，实际 {got}"
        # 同日期存在带标记版本时，带标记者优先
        marked = _write(d, "腾讯控股-00700-7.00-8.0-复盘-2026-08-23.html",
                        FAKE_REPORT)
        got = E.find_prev_report("00700", d, include_unmarked=True)
        assert got == marked, f"同日期应优先带标记版本，实际 {got}"
        # 无标记版本日期更新时，宽松档取无标记新版
        got = E.find_prev_report("00700", d, include_unmarked=True)
        _write(d, "腾讯控股-00700-6.50-7.0-2026-08-30.html",
               "<html><body>更新的无标记</body></html>")
        got = E.find_prev_report("00700", d, include_unmarked=True)
        assert got.endswith("2026-08-30.html"), f"日期最新者应胜出，实际 {got}"
        assert E.find_prev_report("00700", d) == marked, "严格档不受宽松档影响"
    print("OK find_prev_report --include-unmarked（宽松命中 / 同日期带标记优先 / 严格档不受影响）")


def test_extract_anchors():
    with tempfile.TemporaryDirectory() as d:
        p = _write(d, "测试股份-600000-7.50-6.5-2026-08-08.html", FAKE_REPORT)
        out = E.extract(p)
    assert out["company"] == "测试股份" and out["code"] == "600000"
    assert out["date"] == "2026-08-08"
    assert out["prev"]["quality"] == 7.5 and out["prev"]["valuation"] == 6.5
    assert out["prev"]["timing"] == 5.5
    assert out["prev"]["target_range"] == "400-500"
    print("OK extract 锚点（公司/代码/日期/三轨分/目标价区间）")


if __name__ == "__main__":
    test_find_prev_report()
    test_find_include_unmarked()
    test_extract_anchors()
    print("全部 3 项测试通过")
