#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""test_extract_review.py — extract_review 回测触发判定与锚点提取回归测试（无网络，直接 python 运行）"""
import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import extract_review as E

MARK = "<!-- generated by render_report.py v4.5 -->"

FAKE_REPORT = f"""<html><body>
<h1>测试股份（600000）</h1>
<span class="topbar-tag active">2026-08-08</span>
<div class="hero-track quality"><div class="s-label">质量分</div><div class="s-value">7.50</div></div>
<div class="hero-track valuation"><div class="s-label">估值分</div><div class="s-value">6.5</div></div>
<div class="hero-timing-mini">时机分 <span class="tv">5.50</span></div>
<div class="d-item"><div class="d-label">目标价区间（12个月）</div><div class="d-value">400-500<span class="unit"> 元</span></div><div class="d-sub">基础情景</div></div>
</body></html>{MARK}"""


def _write(d, name, content):
    p = os.path.join(d, name)
    with open(p, "w", encoding="utf-8") as f:
        f.write(content)
    return p


def test_find_prev_report():
    with tempfile.TemporaryDirectory() as d:
        old = _write(d, "测试股份-600000-7.50-6.5-2026-08-08.html", FAKE_REPORT)
        # 更新的同代码报告应胜出
        _write(d, "测试股份-600000-7.80-6.8-复盘-2026-08-20.html", FAKE_REPORT)
        # 无渲染器标记的手写产物必须被排除，哪怕日期更新
        _write(d, "测试股份-600000-9.99-9.9-2026-08-25.html",
               FAKE_REPORT.replace(MARK, ""))
        # 其他代码不相关
        _write(d, "别的公司-600001-8.0-8.0-2026-08-26.html", FAKE_REPORT)
        # 文件名无日期不算
        _write(d, "测试股份-600000-无日期.html", FAKE_REPORT)
        got = E.find_prev_report("600000", d)
        assert got.path and got.path.endswith("2026-08-20.html"), f"应取最新的带标记版本，实际 {got}"
        assert got.status == E.ST_FOUND
    # 有候选但全被严格档排除 → 哨兵给 excluded（不再静默 None）
    with tempfile.TemporaryDirectory() as d2:
        _write(d2, "测试股份-600000-9.9-9.9-2026-08-25.html", "<html>无标记</html>")
        r = E.find_prev_report("600000", d2)
        assert r.path is None and r.status == E.ST_EXCLUDED
        assert E.find_prev_report("600000", d2).status == E.ST_EXCLUDED  # 幂等
    print("OK find_prev_report（最新日期 / 无标记排除→excluded / 他代码排除 / 幂等）")


def test_find_include_unmarked():
    """宽松档：无标记的 pre-v4.3 旧报告参与匹配；同日期带标记者优先。"""
    with tempfile.TemporaryDirectory() as d:
        unmarked = _write(d, "腾讯控股-00700-6.93-8.2-复盘-2026-08-23.html",
                          "<html><body>pre-v4.3 无标记</body></html>")
        assert E.find_prev_report("00700", d).path is None, "严格档仍须排除无标记"
        got = E.find_prev_report("00700", d, include_unmarked=True)
        assert got.path == unmarked, f"宽松档应命中无标记旧报告，实际 {got.path}"
        # 同日期存在带标记版本时，带标记者优先
        marked = _write(d, "腾讯控股-00700-7.00-8.0-复盘-2026-08-23.html",
                        FAKE_REPORT)
        got = E.find_prev_report("00700", d, include_unmarked=True)
        assert got.path == marked, f"同日期应优先带标记版本，实际 {got.path}"
        # 无标记版本日期更新时，宽松档取无标记新版
        _write(d, "腾讯控股-00700-6.50-7.0-2026-08-30.html",
               "<html><body>更新的无标记</body></html>")
        got = E.find_prev_report("00700", d, include_unmarked=True)
        assert got.path.endswith("2026-08-30.html"), f"日期最新者应胜出，实际 {got.path}"
        assert E.find_prev_report("00700", d).path == marked, "严格档不受宽松档影响"
    print("OK find_prev_report --include-unmarked（宽松命中 / 同日期带标记优先 / 严格档不受影响）")


def test_extract_anchors():
    with tempfile.TemporaryDirectory() as d:
        p = _write(d, "测试股份-600000-7.50-6.5-2026-08-08.html", FAKE_REPORT)
        out = E.extract(p)
    assert out["company"] == "测试股份" and out["code"] == "600000"
    assert out["date"] == "2026-08-08"
    assert out["prev"]["quality"] == 7.5 and out["prev"]["valuation"] == 6.5
    assert out["prev"]["timing"] == 5.5
    assert out["prev"]["target_range"] == "400-500"
    print("OK extract 锚点（公司/代码/日期/三轨分/目标价区间）")


def test_extract_date_no_topbar():
    """v4.7 起模板删顶栏：日期改从 Hero 副标题「报告日期：」提取，旧版顶栏路径仍兼容。"""
    new_fmt = FAKE_REPORT.replace(
        '<span class="topbar-tag active">2026-08-08</span>',
        '<div class="subtitle">测试行业｜报告日期：2026-08-19</div>')
    with tempfile.TemporaryDirectory() as d:
        p = _write(d, "测试股份-600000-7.50-6.5-2026-08-19.html", new_fmt)
        out = E.extract(p)
        p2 = _write(d, "测试股份-600000-7.50-6.5-2026-08-08.html", FAKE_REPORT)
        out2 = E.extract(p2)
    assert out["date"] == "2026-08-19", f"新版（无顶栏）日期提取失败: {out.get('date')}"
    assert out2["date"] == "2026-08-08", f"旧版（顶栏）日期提取回退: {out2.get('date')}"
    print("OK extract 日期双路径（新版副标题 / 旧版顶栏兼容）")


def test_find_tail_sniff_large_file():
    """v4.9 大 HTML 只读头尾判定：>8KB 报告（渲染标记在文件末尾 </body> 前）仍能命中。"""
    with tempfile.TemporaryDirectory() as d:
        # 中部用纯 ASCII 填充把文件撑过 8KB，MARK 仍在文件末尾（渲染标记固定在尾部）——头尾读取必须命中
        big = "x" * 40000 + FAKE_REPORT
        p = _write(d, "测试股份-600000-7.50-6.5-2026-08-08.html", big)
        assert os.path.getsize(p) > 8192, "夹具必须是大文件分支（>8KB）"
        got = E.find_prev_report("600000", d)
        assert got.path == p, f"大文件尾部标记应命中，实际 {got.path}"
    print("OK find_prev_report 大文件（头尾读取命中尾部渲染标记）")


def test_norm_code_and_find_variants():
    """代码归一化：600000 / 600000.SH / sh600000 三种写法等价命中同一份报告。"""
    assert E.norm_code("600000") == "600000"
    assert E.norm_code(" 600000.SH ") == "600000"
    assert E.norm_code("sh600000") == "600000"
    assert E.norm_code("SZ000063") == "000063"
    assert E.norm_code("00700.HK") == "00700", "港股 5 位前导零必须保留"
    assert E.norm_code("bj920982") == "920982"
    assert E.norm_code("") == "" and E.norm_code(None) == ""
    with tempfile.TemporaryDirectory() as d:
        p = _write(d, "测试股份-600000-7.50-6.5-2026-08-08.html", FAKE_REPORT)
        for c in ("600000", "600000.SH", "sh600000", "600000.sz", " SH600000 "):
            r = E.find_prev_report(c, d)
            assert r.path == p, f"{c!r} 应归一后命中，实际 {r.path}"
    print("OK norm_code + 三种代码写法等价命中")


def test_find_sentinel_status():
    """结构化哨兵三情形：无候选 / 有报告但代码不匹配 / 有同代码候选但被严格档排除。"""
    with tempfile.TemporaryDirectory() as d:
        r = E.find_prev_report("600000", d)
        assert r.path is None and r.status == E.ST_NO_CANDIDATES, "空目录 = no_candidates"
        _write(d, "随手笔记.html", "<html>非报告</html>")   # 不可解析且不像报告 → 仍算无候选
        assert E.find_prev_report("600000", d).status == E.ST_NO_CANDIDATES
        _write(d, "别的公司-600001-8.0-8.0-2026-08-26.html", FAKE_REPORT)
        r = E.find_prev_report("600000", d)
        assert r.path is None and r.status == E.ST_NO_CODE_MATCH, f"实际 {r.status}"
        _write(d, "测试股份-600000-9.9-9.9-2026-08-25.html", "<html>无标记</html>")
        r = E.find_prev_report("600000", d)
        assert r.path is None and r.status == E.ST_EXCLUDED, f"实际 {r.status}"
        assert E.find_prev_report("600000", d, include_unmarked=True).status == E.ST_FOUND, \
            "宽松档下同一目录应转为命中"
    print("OK find_prev_report 哨兵（no_candidates / no_code_match / excluded / 宽松转命中）")


def test_find_recursive_subdir():
    """递归子目录命中（--dir 语义）：报告埋在嵌套目录里也能找到。"""
    with tempfile.TemporaryDirectory() as d:
        sub = os.path.join(d, "2026", "08")
        os.makedirs(sub)
        p = _write(sub, "测试股份-600000-7.50-6.5-2026-08-08.html", FAKE_REPORT)
        r = E.find_prev_report("600000", d)
        assert r.path == p and r.status == E.ST_FOUND, f"递归子目录应命中，实际 {r.path}"
    print("OK find_prev_report 递归子目录命中")


def test_find_prunes_ignored_dirs():
    """v4.10.3 审计：_archive/artifacts/隐藏目录被剪枝——其中的测试夹具不参与匹配，
    否则 CWD=仓库根时 artifacts 里的同名报告会误进回测模式；正常子目录仍递归扫描。"""
    with tempfile.TemporaryDirectory() as d:
        for skip in ("_archive", "artifacts", ".hidden", "__pycache__"):
            sub = os.path.join(d, skip)
            os.makedirs(sub)
            _write(sub, "测试股份-600000-9.99-9.9-复盘-2026-08-30.html", FAKE_REPORT)
        r = E.find_prev_report("600000", d)
        assert r.path is None and r.status == E.ST_NO_CANDIDATES, \
            f"被剪枝目录内的报告不得参与匹配，实际 {r}"
        sub = os.path.join(d, "2026")
        os.makedirs(sub)
        p = _write(sub, "测试股份-600000-7.50-6.5-2026-08-08.html", FAKE_REPORT)
        r = E.find_prev_report("600000", d)
        assert r.path == p, f"正常子目录应仍被扫描，实际 {r.path}"
    print("OK find_prev_report 剪枝（_archive/artifacts/隐藏目录不扫，正常子目录仍扫）")


def test_parse_failure_only_is_no_candidates():
    """v4.10.3 审计：解析失败文件不计入候选——目录里只有「像报告但解析失败」的文件时，
    哨兵必须是 no_candidates（不得报 excluded：那会把用户误导去加 --include-unmarked）。"""
    import contextlib
    import io
    with tempfile.TemporaryDirectory() as d:
        _write(d, "测试股份-600000-无日期.html", FAKE_REPORT)   # 像报告但解析失败
        _write(d, "600000-2026-08-08.html", FAKE_REPORT)        # 同上
        buf = io.StringIO()
        with contextlib.redirect_stderr(buf):
            r = E.find_prev_report("600000", d)
    assert r.path is None and r.status == E.ST_NO_CANDIDATES, \
        f"解析失败文件不得计为候选或排除，实际 {r.status}"
    print("OK 解析失败文件不计入候选（哨兵=no_candidates）")


def test_parse_failure_hint():
    """「像报告但文件名解析失败」打 [跳过: …] 到 stderr；不像报告的静默跳过。"""
    import contextlib
    import io
    with tempfile.TemporaryDirectory() as d:
        _write(d, "测试股份-600000-无日期.html", FAKE_REPORT)   # 像报告（公司名 + 代码）
        _write(d, "600000-2026-08-08.html", FAKE_REPORT)       # 像报告（6 位代码）
        _write(d, "随手笔记.html", "<html>x</html>")           # 不像报告：不提示
        buf = io.StringIO()
        with contextlib.redirect_stderr(buf):
            E.find_prev_report("600000", d)
        err = buf.getvalue()
    assert "[跳过: 文件名无法解析 测试股份-600000-无日期.html]" in err, err
    assert "[跳过: 文件名无法解析 600000-2026-08-08.html]" in err, err
    assert "随手笔记" not in err, f"不像报告的不该提示: {err}"
    print("OK 解析失败提示（像报告的才提示 / 不像报告的静默）")


def test_cli_find_dir_and_messages():
    """CLI 出口：--dir（含 = 形式）+ 代码后缀归一化命中；三情形文案分明（subprocess 直跑，无网络）。"""
    import subprocess
    script = os.path.join(os.path.dirname(os.path.abspath(__file__)), "extract_review.py")

    def run(*a):
        return subprocess.run([sys.executable, script] + list(a),
                              capture_output=True, text=True, encoding="utf-8")
    with tempfile.TemporaryDirectory() as d:
        sub = os.path.join(d, "nested")
        os.makedirs(sub)
        _write(sub, "测试股份-600000-7.50-6.5-2026-08-08.html", FAKE_REPORT)
        r = run("--find", "600000.SH", "--dir", d)          # 后缀归一 + 递归 + 空格形式
        assert r.returncode == 0 and "发现同代码旧报告" in r.stderr, r.stderr
        assert '"code": "600000"' in r.stdout, "应直接输出提取结果"
        r = run("--find", "sh600000", "--dir=" + d)         # = 形式
        assert r.returncode == 0 and "发现同代码旧报告" in r.stderr, r.stderr
    with tempfile.TemporaryDirectory() as d2:
        r = run("--find", "600000", "--dir", d2)
        assert "没有可解析的报告文件" in r.stderr, r.stderr
        _write(d2, "别的公司-600001-8.0-8.0-2026-08-26.html", FAKE_REPORT)
        r = run("--find", "600000", "--dir", d2)
        assert "未找到 600000 的脚本生成旧报告" in r.stderr, r.stderr
        _write(d2, "测试股份-600000-9.9-9.9-2026-08-25.html", "<html>无标记</html>")
        r = run("--find", "600000", "--dir", d2)
        assert "已按严格档排除" in r.stderr and "--include-unmarked" in r.stderr, r.stderr
        r = run("--find", "600000", "--dir", os.path.join(d2, "不存在"))
        assert r.returncode == 1 and "目录不存在" in r.stderr, r.stderr
    print("OK CLI --dir/归一化命中 + 三情形文案 + 坏目录报错")


def test_cli_dir_missing_value_errors():
    """v4.10.3 审计：--dir 缺值（或值恰为另一个 --flag）→ 明确报错 exit 1，不再静默回落 "."。"""
    import subprocess
    script = os.path.join(os.path.dirname(os.path.abspath(__file__)), "extract_review.py")

    def run(*a):
        return subprocess.run([sys.executable, script] + list(a),
                              capture_output=True, text=True, encoding="utf-8")
    r = run("--find", "600000", "--dir")
    assert r.returncode == 1 and "--dir 缺少目录参数" in r.stderr, (r.returncode, r.stderr)
    r = run("--find", "600000", "--dir", "--include-unmarked")
    assert r.returncode == 1 and "--dir 缺少目录参数" in r.stderr, (r.returncode, r.stderr)
    r = run("--find", "600000", "--dir=")
    assert r.returncode == 1 and "--dir= 后缺少目录参数" in r.stderr, (r.returncode, r.stderr)
    print("OK CLI --dir 缺值报错（缺值 / 值是他 flag / --dir= 空值 均 exit 1）")


def test_parse_report_name():
    """文件名解析唯一 owner 的三代命名口径（score_calibration/monthly_checkup 复用本函数）。"""
    # 新命名：公司-代码-质量分-估值分-日期
    r = E.parse_report_name("宝丰能源-600989-7.00-3.9-2026-09-02.html")
    assert r == {"company": "宝丰能源", "code": "600989", "quality": 7.0,
                 "valuation": 3.9, "date": "2026-09-02", "is_review": False}
    # 回测版：带「-复盘-」段
    r = E.parse_report_name("万华化学-600309-6.74-7.4-复盘-2026-08-26.html")
    assert r["is_review"] is True and r["code"] == "600309" and r["date"] == "2026-08-26"
    # 旧 _ 分隔命名（pre-v4.0 单轨综合分）：valuation=None，is_review=False
    r = E.parse_report_name("中国神华_601088_6.72_2026-08-07.html")
    assert r["code"] == "601088" and r["quality"] == 6.72
    assert r["valuation"] is None and r["is_review"] is False
    # 港股 5 位代码前导零保留；北交所 92 段 6 位正常
    assert E.parse_report_name("腾讯控股-00700-6.93-8.2-复盘-2026-08-23.html")["code"] == "00700"
    assert E.parse_report_name("北证样本-920982-5.0-6.0-2026-08-01.html")["code"] == "920982"
    # 边界：无日期 / 非报告 / 新命名缺一个分数段 → None
    assert E.parse_report_name("无日期-600989-6.0-5.0.html") is None
    assert E.parse_report_name("随手笔记.html") is None
    assert E.parse_report_name("测试股份-600000-无日期.html") is None
    assert E.parse_report_name("公司-600989-7.0-2026-08-01.html") is None
    # 接受路径入参（取 basename）
    r = E.parse_report_name(os.path.join("dir", "中兴通讯-000063-4.92-2.3-2026-08-24.html"))
    assert r["code"] == "000063" and r["date"] == "2026-08-24"
    print("OK parse_report_name（三代命名 + 港股/北交所 + 边界排除 + 路径入参）")


def test_find_prev_report_legacy_naming():
    """旧 _ 分隔命名（pre-v4.0）经统一解析口径后也参与回测触发匹配。"""
    with tempfile.TemporaryDirectory() as d:
        p = _write(d, "中国神华_601088_6.72_2026-08-07.html", FAKE_REPORT)
        assert E.find_prev_report("601088", d).path == p, "旧 _ 命名带标记应命中"
        assert E.find_prev_report("00700", d).path is None, "代码不一致不命中"
    print("OK find_prev_report 旧 _ 命名（合并口径后覆盖旧一代报告）")


if __name__ == "__main__":
    test_parse_report_name()
    test_find_prev_report()
    test_find_prev_report_legacy_naming()
    test_find_include_unmarked()
    test_extract_anchors()
    test_extract_date_no_topbar()
    test_find_tail_sniff_large_file()
    test_norm_code_and_find_variants()
    test_find_sentinel_status()
    test_find_recursive_subdir()
    test_find_prunes_ignored_dirs()
    test_parse_failure_only_is_no_candidates()
    test_parse_failure_hint()
    test_cli_find_dir_and_messages()
    test_cli_dir_missing_value_errors()
    print("全部 15 项测试通过")
